LappleApple/awesome-leading-and-managing

MAINTAINERS.md

I also make the maintainers list a bulleted-list

move Lauri onto her own line

---

Onboarding.md

Converted word file to markdown. Did a quick check for typos. Let me know if somethings's missing :)

Onboarding doc

---

README.md
Time-Management-and-Meetings.md

There are a few places I summarized a bit more, specifically, "How to
Take Back Your Workday" has a really long writeup.
Chunks of 'Smarter Management' are missing, as they did not seem to fit
in here, but potentially another section.

Addition of Time Management and Meetings section

---

Influence-Delegation-and-Decision-Making.md
README.md

Updated now my summary of the Influence-Delegation-Decision Making part. Removed the uniqueHR text and all other text parts where the source was not clear. 😄

Influence delegation decision

---

Culture.md
Hiring-and-Firing.md
README.md

Moved up to "How to interview"
This area seems a bit tricky, as some of this is the 'post' interview
evaluation and/or fits into culture.
I've moved one to culture, since it
deals more with internally growing your team, and only moderately
related to hiring in and of itself.

Start of Hiring and firing

---

Hiring-and-Firing.md

Add new article around hiring biases

---

Transitioning to Management.md

Excellent bunch of things you should ask yourself before taking the route into management

Adding "So You Think You Want to Manage?"

---

Giving-Feedback-Praise-and-Advice.md

Compilation on resources about giving and receiving feedbacks

Giving feedback praise and advice

---

Transitioning to Management.md

This is the article I wish I had when I made the transition from IC to manager (before giving up and heading back to tech lead)

Add link to 90-day plan for new engineering managers

---

Leadership-Philosophies-and-Styles.md

HBR article by Kenneth Mikkelsenand Harold Jarche

Adding The Best Leaders Are Constant Learners

---

Motivation-Retention.md

Finishing #7 the chapter "Motivation and retention" is now finished 😄

Motivation and retention

---

Transitioning to Management.md

I'm not sure this is the kind of form or section for this entry, but I'm reading this book and I find it really inspiring. It could be perfect for a section about transitioning to management as it offer a bunch of examples and suggestions for managers at different levels.

Adds The Manager's Path by Camille Fournier

---

Transitioning to Management.md

Proposal on how to mark resources that require buying

Update Transitioning to Management.md

---

Conflict-Resolution-Postmortems-Retrospectives.md

https://github.com/josephearl/awesome-retrospectives

Add Awesome Retrospectives to retrospectives

---

Hiring-and-Firing.md

https://github.com/PeterCookDev/awesome-leading-and-managing

Added Applied Humaning for Technical Interviews

---

Culture.md

Topic: The importance of matching people to the right task

Adding article to the culture list.

---

Leadership-for-Developers.md

Thanks Lauri for adding references to my book and blog!
Here's the addition we discussed on Twitter, the Agile Self-assessment Game. Let me know if this is what you are looking for?

Added Agile Self-assessment Game

---

Giving-Feedback-Praise-and-Advice.md

Added an exercise that can be very effective to give and get feedback from peers

Added perfection game

---

Leadership-Philosophies-and-Styles.md

I've added a highly popular post which gives an overview of the many leadership styles that Scrum masters can learn and apply.

Post on leadership styles for Scrum masters

---

Leadership-for-Developers.md

My blog post on how to consider 'Push' in (agile) teams
Signed-off-by: Paul Adams <paul@baggerspion.net>

Added 'Satisficery Engineering'

---

Transitioning to Management.md

Manager Tools Podcast is a good source of information for new Managers to learn from experienced ones to step up their game. 
Added the link to maintain order. :)

Added link to Manager Tools podcast

---

One-on-Ones.md

Book recommendation useful for 1-on-1's

Added info about Difficult conversations

---

Culture.md

Add Creating Psychological Safety link

---

Culture.md

The original Culture Google Doc has a section about Discrimination and Harassment but there is no link to the original source, so I have started looking for other resources that fall into this category.

Add Discrimination and Harassment section

---

Hiring-and-Firing.md

Adding How to Conduct a Good Programming Interview by Li Haoyi

Add How to Conduct a Good Programming Interview

---

Hiring-and-Firing.md
Transitioning to Management.md

The interviewing ones have been sitting around half finished since shortly after my last PR.  But I found some time this AM while Ms. 6 was in a class to finish them and add the VPE article you asked for on Twitter.

Articles on interviewing and leadership

---

Hiring-and-Firing.md

Not totally sure about the best way to format this-- There's no real subtitle for the piece, I just gave it a pseudo subtitle with a synopsis.

Add The Rolodex

---

Conflict-Resolution-Postmortems-Retrospectives.md

Not all the scenarios are about Conflict Resolution, but seemed the
closest category that makes sense.

Add "These 13 Exercises Will Prepare You for Work's Toughest Situations"

---

Transitioning to Management.md

It was pointing to the wrong article. Updated it!

Fixes wrong url

---

For-Developers-Teamwork-TechDebt.md

Adding: The Senior Engineer’s Guide to Helping Others Make Decisions

help_others_make_decisions

---

Leader-List.md

I'm open for conversations - added myself :)

idvoretskyi's added

---

Onboarding.md

Adding my presentation from a past CTO Summit Sydney on ways to think about Dev Onboarding.  There are 10 questions that help ensure Onboarding program is focused on best outcomes.  It is not a how-to article, as I believe that each org is different and needs to customise the program for its own unique situation.

Presentation from past CTO Summit Sydney

---

CONTRIBUTING.md

Updated the address to a working link

Broken link for changing a pull request

---

Transitioning to Management.md

I am proposing adding 'Communicate Like a Boss' talk from Kathryn Koehler to the Transitioning from Individual Contributor to Manager section.

Adding 'Communicate Like a Boss'

---

Leader-List.md

making sure Intuit is part of the broader community

adding Intuit CEO

---

Meetings-and-Time-Management.md

Remove article which is no longer available.

Remove article from Meetings-and-Time-Management.md

---

README.md

Change typo; reference: https://www.brainyquote.com/quotes/lao_tzu_121709

Change Typo in Lao Tzu Quote

---

Influencing-Others.md

Hey @LappleApple 
minor update: fixing broken link.
Cheers!

Fixing link about front-liners

---

Transitioning to Management.md

Hey @LappleApple 
I've noticed a few broken links and a styling error in "Transitioning to Management". I've fixed these quickly.
Cheers,
Peter

Updating "Transitioning to Management"

---

Leading-Leaders.md

Updating the "Leading Leaders" with summary of "Great Leaders Have No Rules" by Kevin Kruse. Having made the transition from an engineer to a manager to managing managers, lot of the points resonate - especially around "Lead with love", "Show Weakness" and "Leadership is not a choice".

Update with book summary

---

Building-Teams.md

Hey @LappleApple 
just fixing a video link here.
Cheers,
Peter

Fixing link to "Building Great Teams: Culture and Core Protocols"

---

Conflict-Prevention-Resolution.md

"Three Ways To Cool The Conflict"'s link was broken, this is just updating it :) Thanks for this wonderful resource

Update broken link

---

Hiring-and-Interviewing.md

The link for 'Improving Our Engineering Interview Process - by Jeff Jenkins and David Park' is broken. Update the file with the correct Medium link.

Update broken link in Hiring-and-Interviewing.md

---

For-Developers-Teamwork-TechDebt.md
The-CTO-role.md

Hi,
Stjepan from Manning here. I thought this title might be a good match for your list. Thank you for considering it.
Best,

Added Think Like a CTO (book)

---

For-Developers-Teamwork-TechDebt.md

Hi,
Stjepan here from Manning. I thought this title might be a good match for your list. Thank you for considering it.
Best,

Added Lead Developer Career Guide
